name: Print Hello world
on:
   push:
jobs:
    print:
        runs-on: macOS-latest
        steps:
            - name: Print Hello
              run: echo "Hello World" 
    second-job: 
        runs-on: macOS-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - name: Installs dependencies
              run: npm install
            - name: run test
              run: npm test 