name: Print Hello world
on:
   push:
jobs:
    print:
        runs-on: macOS-latest
        steps:
            - name: Print Hello
              run: echo "Hello World" 
    second-job: 
        runs-on: macOS-latest
        steps:
            - name: Print from second job
              run: ls 
      