name: Print Hello world
on:
   push:
jobs:
    print:
        runs-on: macOS-latest
        steps:
            - name: Print Hello
              run: echo "Hello World" 
    second-job: 
        runs-on: macOS-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - name: Repo cloning
              uses: actions/checkout@v4 
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 18.x
            - name: Installs dependencies
              run: npm ci
            - name: Run test
              run: npm test 